##########################################
#                                        #
#       Tadukoo Bible Books Config       #
##########################################
# How many chapters are made before notifying you.
# Set to 0 to never be notified.
chapter-notify: 5

# The settings below are how to check the bookconfig.yml file for the given translation.
# Create will overwrite books even if they already exist.
# Correct will overwrite incorrect parts of books and ignore others.
# Check will simply check if each book exists and create them if they don't.
# Ignore will do nothing.
KJV:
  all:
    check: true
    type: check
  list:
    check: true
    type: check
  Genesis:
    check: true
    type: check
  Exodus:
    check: true
    type: check
  Leviticus:
    check: true
    type: check
  Numbers:
    check: true
    type: check
  Deuteronomy:
    check: true
    type: check
  Joshua:
    check: true
    type: check
  Judges:
    check: true
    type: check
  Ruth:
    check: true
    type: check
  1Samuel:
    check: true
    type: check
  2Samuel:
    check: true
    type: check
  1Kings:
    check: true
    type: check
  2Kings:
    check: true
    type: check
  1Chronicles:
    check: true
    type: check
  2Chronicles:
    check: true
    type: check
  Ezra:
    check: true
    type: check
  Nehemiah:
    check: true
    type: check
  Esther:
    check: true
    type: check
  Job:
    check: true
    type: check
  Psalms:
    check: true
    type: check
  Proverbs:
    check: true
    type: check
  Ecclesiastes:
    check: true
    type: check
  SongofSongs:
    check: true
    type: check
  Isaiah:
    check: true
    type: check
  Jeremiah:
    check: true
    type: check
  Lamentations:
    check: true
    type: check
  Ezekiel:
    check: true
    type: check
  Daniel:
    check: true
    type: check
  Hosea:
    check: true
    type: check
  Joel:
    check: true
    type: check
  Amos:
    check: true
    type: check
  Obadiah:
    check: true
    type: check
  Jonah:
    check: true
    type: check
  Micah:
    check: true
    type: check
  Nahum:
    check: true
    type: check
  Habbakuk:
    check: true
    type: check
  Zephaniah:
    check: true
    type: check
  Haggai:
    check: true
    type: check
  Zechariah:
    check: true
    type: check
  Malachi:
    check: true
    type: check
  Matthew:
    check: true
    type: check
  Mark:
    check: true
    type: check
  Luke:
    check: true
    type: check
  John:
    check: true
    type: check
  Acts:
    check: true
    type: check
  Romans:
    check: true
    type: check
  1Corinthians:
    check: true
    type: check
  2Corinthians:
    check: true
    type: check
  Galatians:
    check: true
    type: check
  Ephesians:
    check: true
    type: check
  Philippians:
    check: true
    type: check
  Colossians:
    check: true
    type: check
  1Thessalonians:
    check: true
    type: check
  2Thessalonians:
    check: true
    type: check
  1Timothy:
    check: true
    type: check
  2Timothy:
    check: true
    type: check
  Titus:
    check: true
    type: check
  Philemon:
    check: true
    type: check
  Hebrews:
    check: true
    type: check
  James:
    check: true
    type: check
  1Peter:
    check: true
    type: check
  2Peter:
    check: true
    type: check
  1John:
    check: true
    type: check
  2John:
    check: true
    type: check
  3John:
    check: true
    type: check
  Jude:
    check: true
    type: check
  Revelation:
    check: true
    type: check
